Update securesubmit.php
hps/heartland-opencart-2.3-plugin pull request #5
Opened 2017-02-22 16:03 UTC by ttnnkkrr

2017-02-23 16:47 UTC, SenthilKumar-86 requested changes

2017-02-23 16:47 UTC, SenthilKumar-86 commented on catalog/controller/extension/payment/securesubmit.php
>          }
is it possible to replace these three if conditions with this one line code, like 
$this->session->data[$HPS_KEY]['lastErrorTime'] = (!empty($this->session->data[$HPS_KEY]['lastErrorTime'])) ? $this->session->data[$HPS_KEY]['lastErrorTime'] : 0;

2017-02-23 16:47 UTC, SenthilKumar-86 commented on catalog/controller/extension/payment/securesubmit.php
>          $HPS_KEY = $this->securesubmit_fraud_fail_var;
shall we add a condition here to make sure $this->securesubmit_fraud_fail_var is not empty?

2017-02-23 19:48 UTC, ttnnkkrr commented on catalog/controller/extension/payment/securesubmit.php
>          }
@SenthilKumar-86 I suppose we could but dont you think this way is easier to read?

2017-02-23 19:53 UTC, ttnnkkrr commented
@SenthilKumar-86 on $this->securesubmit_fraud_fail_var good catch

2017-02-24 14:48 UTC, SenthilKumar-86 approved these changes

2017-02-24 15:46 UTC, SenthilKumar-86 commented on catalog/controller/extension/payment/securesubmit.php
>          }
Yes i agree readability wise it's easier..

2017-02-24 16:12 UTC, SenthilKumar-86 approved these changes

2017-02-24 16:22 UTC, SenthilKumar-86 commented
Functionality wise, When we buy product,  orders listed as canceled status in admin side. Can you please check it.

2017-02-24 16:26 UTC, SenthilKumar-86 requested changes
Functionality needs to be checked

2017-02-24 18:24 UTC, SenthilKumar-86 approved these changes

2017-03-16 14:27 UTC, merged