Secure submit to GlobalPayment JS migration
hps/heartland-opencart-2.3-plugin pull request #9
Opened 2024-03-19 09:07 UTC by mayur-vachchewar

2024-03-27 16:54 UTC, MSmedal requested changes
Looks great! Just a bit of housekeeping to finish

2024-03-27 16:54 UTC, MSmedal commented on admin/controller/extension/payment/securesubmit.php
> +
```suggestion
```

2024-03-27 16:54 UTC, MSmedal commented on catalog/view/stylesheet/securesubmit.css
>      padding-left:none;
Not an issue you introduced, but can you fix this? ['none' isn't a value of padding-left](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-left)

2024-03-27 16:54 UTC, MSmedal commented on catalog/view/theme/default/template/extension/payment/securesubmit.tpl
I'm having some system issues when I try to spin up an OpenCart 2.3 site to run this one. Could you upload a snippet of the card info input fields we're creating for my reference?

2024-03-28 05:53 UTC, mayur-vachchewar commented on catalog/view/theme/default/template/extension/payment/securesubmit.tpl
> I'm having some system issues when I try to spin up an OpenCart 2.3 site to run this one. Could you upload a snippet of the card info input fields we're creating for my reference?

Here is the reference:
![Uploading image.png…]()

2024-03-28 05:54 UTC, mayur-vachchewar commented on catalog/view/theme/default/template/extension/payment/securesubmit.tpl
![image](https://github.com/hps/heartland-opencart-2.3-plugin/assets/88787617/be1bdc8d-1a77-46cf-95c1-e63e8ebf80be)

2024-03-28 12:50 UTC, MSmedal approved these changes

2024-04-04 13:07 UTC, merged